name: Latest douban activities workflow
on:
  schedule:
    # Runs every 2 hour
    - cron: "0 */2 * * *"

jobs:
  update-readme-with-douban-activities:
    name: Update this repo's README with douban  activities
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go run build_readme.go
